name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Create Module Package
      shell: pwsh
      run: |
        # Create a generic release folder (without version in name)
        $releasePath = ".\release\QuickSoft"
        New-Item -Path $releasePath -ItemType Directory -Force
        
        # Copy module files into the release folder
        Copy-Item -Path ".\QuickSoft.ps*1" -Destination $releasePath
        Copy-Item -Path ".\Public" -Destination $releasePath -Recurse
        Copy-Item -Path ".\LICENSE" -Destination $releasePath
        
        # Create the zip file with the version in its name (not the folder)
        $zipName = "QuickSoft.zip"
        Compress-Archive -Path "$releasePath" -DestinationPath "./$zipName"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./QuickSoft-${{ github.ref_name }}.zip
        asset_name: QuickSoft-${{ github.ref_name }}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
